### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by kawashima-mozart** [kawashima-mozart/furima-31646#10]
アプリのURL
 https://furima-31646.herokuapp.com/

basic認証|　admin 
Password| 2222

出品者用アカウント
アドレス|test@mail.com  
Password| test111

購入者用アカウント
アドレス|test2@mail.com
Password|test222

購入用カード
カード番号 | 4242424242424242
-- | --
CVC | 123
有効期限 | 4/23

**Comment by naru6117** [comment]
ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！


**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**
